### PR TITLE
Cleaning up web fitted logos

### PR DESCRIPTION
**Pull request by DouglasHeriot**
Separated the old ones with extra pixels as clearly for the old web UI, vs new ones without extra padding.
Note sizes are now different. (So the logo itself is the same size)

Also:
- Cleaned up OLA O Only.png with anti-alisaing, and higher resolution
- New cleaned-up OLE logo (customised the ‘E’ to refer back to OLA, and balance better)
- Put back development/old original logos - important reference that all the new designs were based off

### CODE REVIEW

**Comment by peternewman** [comment]
Thanks @DouglasHeriot the OLE looks infinitely better than my rubbish efforts in GIMP, the slant is a nice touch. Is it a design decision to have the L and E shorter still, I just couldn't quite match the font size when I tried.

The O only looks much cleaner too, although is there any reason it's still not perfectly square, or is the circle not a perfect circle.

LGTM, just a few comments.

**Comment by peternewman** [comment]
Can we have an O only .pdf too please.

**Comment by DouglasHeriot** [comment]
- The width of the "LE" in "OLE" is straight out of the font – maybe we have slightly different versions of Century Gothic?
- I kerned them so the space between LE is same as OL
- I think the O came straight out of Century Gothic, and it seems it is slightly not quite a circle. (So close it doesn’t matter). The png files came from Illustrator’s Export command, and that’s just the size it chose.
- Added O only in pdf, and reversed png.

**Comment by peternewman** [comment]
I meant the height of the "LE" @DouglasHeriot , rather than the width. Although it looks the same on the "LA". Was the O the original O from Century Gothic? Is the spacing of "OLA"/"OLE" (as normal letters) still the same as the 5 pin XLR "LA"/"LE"?

Would you mind padding the O exports to make them square, or do you feel that should be part of the individual use case?

**Pull request merged**
