### PR TITLE
Add ® to the OLA logo

### PR DESCRIPTION
**Pull request by DouglasHeriot**
Includes web fitted versions at 48px and 48@2x, with the ® at the smallest legibile size.
Didn't add it to 20px version, as it has to too large to be legible.

### CODE REVIEW

**Comment by peternewman** [comment]
Can you manage to squeeze it onto the 48px version too @DouglasHeriot as both UIs are currently still in active usage.

Could we have a reversed one again please. Can we keep the 88px one as @2x again, to signify it's usage.

**Comment by peternewman** [comment]
Again LGTM, just a few comments.

**Comment by peternewman** [comment]
And I think you meant 44px, not 48px in your earlier comment.

**Comment by DouglasHeriot** [comment]
- Oops, you’re correct I got some 48 and 44 mixed up.
- I also agree it should be 44@2x (don’t know why I put 88)
- Added 48px versions, for current web UI
- Added reversed high-res png

**Pull request merged**
